-- Membuat tabel leaderboard
CREATE TABLE IF NOT EXISTS leaderboard (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  name TEXT NOT NULL,
  school_name TEXT NOT NULL,
  score INTEGER NOT NULL,
  time_seconds INTEGER NOT NULL
);

-- Mengaktifkan Row Level Security (RLS)
ALTER TABLE leaderboard ENABLE ROW LEVEL SECURITY;

-- Membuat kebijakan akses (Policy) agar publik bisa melihat (membaca) leaderboard
CREATE POLICY "Public profiles are viewable by everyone."
ON leaderboard FOR SELECT
USING ( true );

-- Membuat kebijakan akses (Policy) agar publik (anon) bisa memasukkan data (insert)
CREATE POLICY "Anyone can insert a score."
ON leaderboard FOR INSERT
WITH CHECK ( true );
